### PR TITLE
Added support for "import" statement

### PR DESCRIPTION
**Pull request by kuashe**
Support ES2015 "import" inside of the "script" in the tag

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
@aMarCruz can you please check this pull request? @kuashe you are the man!!!

**Comment by GianlucaGuarini** [comment]
@kuashe could you fix the tests please?

**Comment by GianlucaGuarini** [comment]
@kuashe it'd be better to pull request on the `dev` branch

**Comment by kuashe** [comment]
@GianlucaGuarini  Gonna fix the tests , i'll do the changes on dev .

**Comment by kuashe** [comment]
@GianlucaGuarini  I'm closing this , reopening for dev.

**Pull request closed without merging**
