### PR TITLE
v2.3.0-beta.6

### PR DESCRIPTION
**Pull request by aMarCruz**
Breaking change:

`compiler.parsers.css.es6` is for babel-core only, because changes in the its API. You need install `babel-preset-es2015` too.

new `compiler.parsers.css.babel` is for old babel 5.8.x

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
[shouldn't they be `compiler.parsers.js.babel`](http://riotjs.com/guide/compiler/#riot-parsers-on-the-browser-and-the-server)?

**Comment by aMarCruz** [comment]
Yes, the new babel 6.0.2 is not compatible with node require, the API of babel-core changed and is not compatible with the previous babel API, so I include support for new babel-core in `css.es6`, so babel 5.8.x users have 2 options: a) install babel-core + babel-preset-es2015, or b) change their scripts for use `<script type="babel">`.

**Comment by aMarCruz** [comment]
The babel change was few hours ago, and thinking more about this, maybe I rushed and es6 should be unchanged.

Anyway, what do you think about a plugin system? some very basic, as declaring a custom parser. This can provide flexibility to users without this problems.

**Comment by aMarCruz** [comment]
@GianlucaGuarini , I revert `parsers.css.es6` to use babel, and `parsers.css.babel` to using babel-core.
And another surprise: in the travis test babel-core is changing `this` to `undefined`. I don't know why, in my local environment is working, and there's no documentation for the new plugins of babel, so I'll mark this as "experimental" in the docs.

Except the babel-core problem, the final riot-compiler v2.3.0 is working now, no more changes.

**Pull request merged**
