### PR TITLE
Preserve whitespace

### PR DESCRIPTION
**Pull request by sethyuan**

### CODE REVIEW

**Comment by sethyuan** [comment]
@GianlucaGuarini I think preserving whitespace should not be an option that you can skip, or at least, preserving whitespace should be on by default.

**Comment by GianlucaGuarini** [comment]
@sethyuan we could add the default here https://github.com/riot/cli/blob/master/lib/options.js#L84-L86 but not in the compiler

**Comment by sethyuan** [comment]
What if users use the compiler API directly? riotjs-loader (for Webpack) for example does this. I think compiler option defaults should be defined within compiler itself.

**Comment by GianlucaGuarini** [comment]
In this case I would use a private variable in the compiler called `defaults` that will be extended when an user will send some custom options to the compile method. @aMarCruz what do you think?

**Comment by aMarCruz** [comment]
The riot.compile function (from compiler 2.3.12) will support an additional parameter: the options for the compiler.
Also, in v2.3.12 the `<pre>` tag preserves whitespace, anything else is a breaking change.

I'll close this PR now, feel free to reopen it if you consider it necessary.

**Pull request closed without merging**
